---
- name: "Initialize environment for SIMP installation"
  vars_files:
    - ../vars/vars.yaml
  hosts: "{{ hosts }}"
  remote_user: ec2-user
  become: true

  tasks:
  - name: Place EPEL Repo
    template:
      src=../files/epel.repo dest=/etc/yum.repos.d/epel.repo
  - name: Install Addtitional packages
    yum:
      name: "{{ packages }}"
      state: latest
  - name: Start and enable apache
    service:
      name: httpd
      state: started
      enabled: yes
